server:
    port: 8443
    #打开注释，则通过【http://localhost/dp-lte】访问
    #context-path: /dp-lte

    ssl:
        key-store: classpath:xjgjpay.pfx
        key-store-password: 214319422710085
        keyStoreType: PKCS12

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
              default:  #默认数据源
                    url: jdbc:mysql://localhost:3306/xjgjpay?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                    username: root
                    password: XIjiao!20@17!GuOjIfmsza!
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
logging:
    file: log\xjgjpay_test.log
myprop:
    api:
        jsxt:
            app-key: #结算系统访问口令生成密钥
                c086d7c29d8c5ba4a49e66f74d163466
            app-url: #结算系统接口url
                https://xjgjapp.com:8443/app/
            jks-name:
                C:\UserData\xjgjpay\xjgj_jsxt_truststore.jks
            jks-pwd:
                XjgjD208
        baofoo:
            url: #宝付支付接口url
                https://vgw.baofoo.com/cutpayment/api/backTransRequest
            version:
                4.0.0.0
            char-set: #宝付接口默认编码格式
                UTF-8
            pfx-name: #商户私钥路径
                C:\UserData\xjgjpay\bfkey_100000276@@100000990.pfx
            pfx-pwd: #商户私钥密码
                123456
            cer-name: #宝付公钥路径
                C:\UserData\xjgjpay\bfkey_100000276@@100000990.cer
            terminal-id: #终端号
                100000990
            member-id: #商户号
                100000276
            data-type: #数据类型json/xml
                json
            biz-type: #接入类型
                0000